import { useMemo, useState } from "react";
import { Check, ChevronRight, CircleAlert, Clock3, Plus, Search, Users, CalendarDays, BriefcaseBusiness, ClipboardList, ShieldCheck, ArrowRight, UserRound } from "lucide-react";
import { AppShell, type View } from "../components/app/AppShell";
import { Badge, Button, Card, EmptyState, Input, Modal, SectionTitle } from "../components/app/Primitives";
import { mockDb, permissions } from "../data/mock";
import { employeeById, getEligibleVacancies, labelFor } from "../services/mockService";
import type { Role } from "../types";

const tone=(s:string):"neutral"|"success"|"warning"|"danger"|"info" =>
  /Aprov|Ativ|Confirm|Conclu|Convert|Acion/.test(s)?"success":/Pendent|Planej|Sobre|standby|Reserva/.test(s)?"warning":/Rejeit|Cancel|Confl/.test(s)?"danger":"neutral";

function PageHeader({title,description,action}:{title:string;description?:string;action?:React.ReactNode}){return <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-1 text-xs font-medium uppercase tracking-wider text-slate-400">Eventa</div><h1 className="text-2xl font-semibold tracking-tight text-slate-950">{title}</h1>{description&&<p className="mt-1 max-w-2xl text-sm text-slate-500">{description}</p>}</div>{action}</div>}

function Dashboard({role}:{role:Role}){
  if(role==="employee") return <EmployeeDashboard/>;
  const stats=[["Funcionárias",mockDb.employees.filter(e=>e.professionalStatus==="Ativa").length,"ativas",Users],["Próximos eventos",mockDb.events.filter(e=>e.status==="Planejado").length,"agendados",CalendarDays],["Vagas abertas",mockDb.vacancies.reduce((n,v)=>n+Math.max(0,v.quantity-v.filled),0),"disponíveis",BriefcaseBusiness],["Candidaturas pendentes",mockDb.applications.filter(a=>a.status==="Pendente").length,"aguardando análise",ClipboardList],["Alocações confirmadas",mockDb.allocations.filter(a=>a.status==="Confirmada").length,"registros",Check],["Sobreaviso",mockDb.reserves.filter(r=>r.status==="standby").length,"em reserva",ShieldCheck]] as const;
  return <><PageHeader title={role==="admin"?"Visão geral":"Painel da gerente"} description="Acompanhe a operação sem indicadores financeiros."/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{stats.map(([label,value,sub,Icon])=><Card key={label} className="p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-slate-400">{sub}</p></div><div className="rounded-xl bg-slate-100 p-2.5 text-slate-600"><Icon size={18}/></div></div></Card>)}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><Card className="p-5"><SectionTitle title="Próximos eventos" subtitle="Os eventos que exigem atenção."/><div className="space-y-2">{mockDb.events.filter(e=>e.status==="Planejado").slice(0,4).map(e=><div key={e.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><div><p className="text-sm font-medium">{e.name}</p><p className="mt-1 text-xs text-slate-500">{new Date(e.date+"T12:00").toLocaleDateString("pt-BR")} · chegada {e.arrival} · início {e.start}</p></div><Badge tone={tone(e.status)}>{e.status}</Badge></div>)}</div></Card>
    <Card className="p-5"><SectionTitle title="Candidaturas aguardando análise"/><div className="space-y-2">{mockDb.applications.filter(a=>a.status==="Pendente").map(a=>{const emp=employeeById(a.employeeId)!;const v=mockDb.vacancies.find(x=>x.id===a.vacancyId)!;return <div key={a.id} className="flex items-center justify-between rounded-xl border border-slate-100 p-3"><div><p className="text-sm font-medium">{emp.name}</p><p className="text-xs text-slate-500">{v.name} · {mockDb.events.find(e=>e.id===a.eventId)?.name}</p></div><Badge tone="warning">Pendente</Badge></div>})}</div></Card></div>
    <Card className="mt-6 p-5"><SectionTitle title="Reservas / sobreaviso" subtitle="Acompanhe o estado das reservas."/><div className="grid gap-3 sm:grid-cols-2">{mockDb.reserves.map(r=>{const emp=employeeById(r.employeeId)!;const ev=mockDb.events.find(e=>e.id===r.eventId)!;return <div key={r.id} className="rounded-xl border border-slate-100 p-4"><div className="flex justify-between"><p className="font-medium">{emp.name}</p><Badge tone={tone(r.status)}>{r.status==="standby"?"Reserva/Sobreaviso":r.status==="triggered"?"Acionada":"Alocação efetiva"}</Badge></div><p className="mt-1 text-sm text-slate-500">{ev.name}</p></div>})}</div></Card>
  </>
}

function EmployeeDashboard(){const eligible=getEligibleVacancies("e1");return <><PageHeader title="Início" description="Tudo o que você precisa para seus próximos trabalhos."/><div className="grid gap-4 md:grid-cols-3"><Card className="p-5 md:col-span-2"><p className="text-sm text-slate-500">Próximo evento confirmado</p><p className="mt-2 text-xl font-semibold">Festa Infantil Encanto</p><p className="mt-1 text-sm text-slate-500">10/10/2026 · chegada 08:00 · início 09:00 · Espaço Villa</p><div className="mt-4"><Badge tone="success">Confirmado</Badge></div></Card><Card className="p-5"><p className="text-sm text-slate-500">Candidaturas pendentes</p><p className="mt-2 text-3xl font-semibold">{mockDb.applications.filter(a=>a.employeeId==="e1"&&a.status==="Pendente").length}</p><p className="mt-1 text-xs text-slate-400">aguardando resposta</p></Card></div><div className="mt-6"><SectionTitle title="Próximas oportunidades" subtitle="Vagas elegíveis para o seu perfil."/><div className="grid gap-4 md:grid-cols-2">{eligible.slice(0,4).map(v=><OpportunityCard key={v.id} vacancy={v.id}/>)}</div></div><Card className="mt-6 p-5"><SectionTitle title="Status de sobreaviso"/><div className="flex items-center gap-3"><ShieldCheck className="text-amber-600"/><div><p className="font-medium">Você possui 1 reserva em acompanhamento.</p><p className="text-sm text-slate-500">O acionamento será informado quando houver necessidade.</p></div></div></Card></>}

function Employees(){const [q,setQ]=useState("");const [open,setOpen]=useState(false);const rows=mockDb.employees.filter(e=>e.name.toLowerCase().includes(q.toLowerCase()));return <><PageHeader title="Funcionárias" description="Cadastro e acompanhamento do quadro profissional." action={<Button onClick={()=>setOpen(true)}><Plus size={16}/> Nova funcionária</Button>}/><Card className="overflow-hidden"><div className="border-b border-slate-100 p-4"><div className="relative max-w-sm"><Search className="absolute left-3 top-2.5 text-slate-400" size={17}/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por nome..." className="pl-9"/></div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Funcionária</th><th className="px-5 py-3">Nível</th><th className="px-5 py-3">Habilidades</th><th className="px-5 py-3">Telefone</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Acesso</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(e=><tr key={e.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-slate-100 text-xs font-semibold">{e.avatar}</div><span className="font-medium">{e.name}</span></div></td><td className="px-5 py-4">{labelFor(mockDb.levels,e.levelId)}</td><td className="px-5 py-4"><div className="flex max-w-xs flex-wrap gap-1">{e.skillIds.map(s=><Badge key={s}>{labelFor(mockDb.skills,s)}</Badge>)}</div></td><td className="px-5 py-4 text-slate-500">{e.phone}</td><td className="px-5 py-4"><Badge tone={e.professionalStatus==="Ativa"?"success":"neutral"}>{e.professionalStatus}</Badge></td><td className="px-5 py-4"><Badge tone={tone(e.accessStatus)}>{e.accessStatus}</Badge></td></tr>)}</tbody></table></div></Card><Modal open={open} onClose={()=>setOpen(false)} title="Nova funcionária"><EmployeeForm onClose={()=>setOpen(false)}/></Modal></>}

function EmployeeForm({onClose}:{onClose:()=>void}){return <div className="space-y-5"><div><h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400">Dados profissionais</h4><div className="mt-3 grid gap-3 sm:grid-cols-2"><Input placeholder="Nome completo"/><Input placeholder="Telefone / WhatsApp"/><select className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option>Nível</option>{mockDb.levels.map(l=><option key={l.id}>{l.name}</option>)}</select><Input placeholder="CPF / dado cadastral"/></div></div><div><h4 className="text-xs font-semibold uppercase tracking-wider text-slate-400">Acesso ao aplicativo</h4><p className="mt-1 text-sm text-slate-500">O acesso é uma configuração independente dos dados profissionais.</p></div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button onClick={onClose}>Salvar mock</Button></div></div>}

function LevelsOrSkills({kind}:{kind:"levels"|"skills"}){const items=kind==="levels"?mockDb.levels:mockDb.skills;const title=kind==="levels"?"Níveis":"Habilidades";return <><PageHeader title={title} description={`Dados cadastráveis de ${title.toLowerCase()}, não opções fixas da regra do sistema.`} action={<Button><Plus size={16}/> Novo {kind==="levels"?"nível":"habilidade"}</Button>}/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map(i=><Card key={i.id} className="flex items-center justify-between p-5"><div><p className="font-medium">{i.name}</p><p className="mt-1 text-xs text-slate-400">{i.active?"Ativo":"Desativado"}</p></div><div className="flex gap-2"><Button variant="ghost">Editar</Button><Button variant="secondary">{i.active?"Desativar":"Ativar"}</Button></div></Card>)}</div></>}

function Events({onView}:{onView:(v:View)=>void}){const [open,setOpen]=useState(false);return <><PageHeader title="Eventos" description="Planejamento, horários e ocupação dos eventos." action={<Button onClick={()=>setOpen(true)}><Plus size={16}/> Novo evento</Button>}/><div className="mb-5 flex gap-2"><Button variant="secondary" onClick={()=>onView("calendar")}>Calendário mensal</Button><Button variant="secondary" onClick={()=>onView("calendar")}>Semanal</Button><Button variant="secondary" onClick={()=>onView("calendar")}>Diário</Button></div><div className="grid gap-4 lg:grid-cols-2">{mockDb.events.map(e=><Card key={e.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-semibold">{e.name}</p><p className="mt-1 text-sm text-slate-500">{new Date(e.date+"T12:00").toLocaleDateString("pt-BR")} · {e.location}</p></div><Badge tone={tone(e.status)}>{e.status}</Badge></div><div className="mt-5 grid grid-cols-3 gap-3 rounded-xl bg-slate-50 p-3 text-center"><div><p className="text-[11px] uppercase text-slate-400">Chegada</p><p className="mt-1 font-semibold text-amber-700">{e.arrival}</p></div><div><p className="text-[11px] uppercase text-slate-400">Início</p><p className="mt-1 font-semibold">{e.start}</p></div><div><p className="text-[11px] uppercase text-slate-400">Término</p><p className="mt-1 font-semibold">{e.end}</p></div></div><div className="mt-4 flex items-center justify-between text-sm"><span className="text-slate-500">Vagas preenchidas</span><span className="font-medium">{e.filledCount}/{e.vacancyCount}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-800" style={{width:`${Math.min(100,e.filledCount/e.vacancyCount*100)}%`}}/></div></Card>)}</div><Modal open={open} onClose={()=>setOpen(false)} title="Criar evento"><EventForm onClose={()=>setOpen(false)}/></Modal></>}

function EventForm({onClose}:{onClose:()=>void}){return <div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-medium">Nome / título<Input className="mt-1" placeholder="Ex.: Festa Infantil Encanto"/></label><label className="text-sm font-medium">Data<Input className="mt-1" type="date"/></label><label className="text-sm font-medium">Local<Input className="mt-1" placeholder="Local do evento"/></label><label className="text-sm font-medium">Horário de chegada<Input className="mt-1" type="time"/></label><label className="text-sm font-medium">Horário de início<Input className="mt-1" type="time"/></label><label className="text-sm font-medium">Horário de término<Input className="mt-1" type="time"/></label><label className="sm:col-span-2 text-sm font-medium">Informações relevantes<textarea className="mt-1 min-h-24 w-full rounded-lg border border-slate-200 p-3 text-sm outline-none" placeholder="Informações liberadas para a equipe"/></label><div className="sm:col-span-2 rounded-lg bg-amber-50 p-3 text-sm text-amber-800"><Clock3 className="mr-2 inline" size={16}/>A chegada é diferente do início do evento e deve ser preenchida separadamente.</div><div className="flex justify-end gap-2 sm:col-span-2"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button onClick={onClose}>Salvar mock</Button></div></div>}

function CalendarView(){return <><PageHeader title="Agenda" description="Visualização operacional em calendário."/><Card className="p-5"><div className="mb-5 flex items-center justify-between"><h3 className="font-semibold">Outubro 2026</h3><div className="flex gap-2"><Button variant="secondary">Mês</Button><Button variant="ghost">Semana</Button><Button variant="ghost">Dia</Button></div></div><div className="grid grid-cols-7 gap-px overflow-hidden rounded-xl bg-slate-200">{["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"].map(d=><div key={d} className="bg-slate-50 p-2 text-center text-xs font-semibold text-slate-400">{d}</div>)}{Array.from({length:35},(_,i)=><div key={i} className="min-h-24 bg-white p-2 text-xs"><span className="text-slate-400">{i+28>30?i-2:i+28}</span>{mockDb.events.filter(e=>Number(e.date.slice(-2))===i+28).map(e=><div key={e.id} className="mt-2 rounded-lg bg-slate-100 p-2 font-medium">{e.name}</div>)}</div>)}</div></Card></>}

function Applications(){const [items,setItems]=useState(mockDb.applications);return <><PageHeader title="Candidaturas" description="Análise manual das manifestações de interesse."/><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="px-5 py-3">Funcionária</th><th className="px-5 py-3">Vaga</th><th className="px-5 py-3">Evento</th><th className="px-5 py-3">Data</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Ação</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map(a=>{const emp=employeeById(a.employeeId)!;const v=mockDb.vacancies.find(x=>x.id===a.vacancyId)!;const ev=mockDb.events.find(x=>x.id===a.eventId)!;return <tr key={a.id}><td className="px-5 py-4 font-medium">{emp.name}</td><td className="px-5 py-4">{v.name}</td><td className="px-5 py-4">{ev.name}</td><td className="px-5 py-4 text-slate-500">{a.date}</td><td className="px-5 py-4"><Badge tone={tone(a.status)}>{a.status}</Badge></td><td className="px-5 py-4">{a.status==="Pendente"&&<div className="flex gap-2"><Button onClick={()=>setItems(xs=>xs.map(x=>x.id===a.id?{...x,status:"Aprovada"}:x))}>Aprovar</Button><Button variant="danger" onClick={()=>setItems(xs=>xs.map(x=>x.id===a.id?{...x,status:"Rejeitada"}:x))}>Rejeitar</Button></div>}</td></tr>})}</tbody></table></div></Card></>}

function Allocations(){return <><PageHeader title="Alocações" description="Alocações confirmadas, conflitos e origens de reserva."/><div className="grid gap-4 lg:grid-cols-2">{mockDb.allocations.map(a=>{const emp=employeeById(a.employeeId)!;const ev=mockDb.events.find(e=>e.id===a.eventId)!;const v=mockDb.vacancies.find(x=>x.id===a.vacancyId)!;return <Card key={a.id} className="p-5"><div className="flex justify-between"><div><p className="font-semibold">{emp.name}</p><p className="mt-1 text-sm text-slate-500">{ev.name} · {v.name}</p></div><Badge tone={tone(a.status)}>{a.status}</Badge></div><div className="mt-4 flex flex-wrap gap-2"><Badge>{a.fromReserve?"Origem: reserva":"Alocação normal"}</Badge>{a.status==="Conflito"&&<Badge tone="danger"><CircleAlert size={13} className="mr-1"/>Conflito de horário</Badge>}{v.filled>=v.quantity&&<Badge tone="warning">Vaga lotada</Badge>}</div></Card>})}</div></>}

function Standby(){const [reserves,setReserves]=useState(mockDb.reserves);return <><PageHeader title="Reserva / Sobreaviso" description="Acompanhe reservas sem confundi-las com alocações efetivas."/><div className="grid gap-4 md:grid-cols-2">{reserves.map(r=>{const emp=employeeById(r.employeeId)!;const ev=mockDb.events.find(e=>e.id===r.eventId)!;return <Card key={r.id} className="p-5"><div className="flex items-start justify-between"><div><p className="font-semibold">{emp.name}</p><p className="mt-1 text-sm text-slate-500">{ev.name}</p></div><Badge tone={tone(r.status)}>{r.status==="standby"?"Reserva/Sobreaviso":r.status==="triggered"?"Acionada":r.status==="allocated"?"Alocação efetiva":"Cancelada/Liberada"}</Badge></div>{r.status==="standby"&&<Button className="mt-5" onClick={()=>setReserves(rs=>rs.map(x=>x.id===r.id?{...x,status:"triggered"}:x))}>Acionar reserva <ArrowRight size={15}/></Button>}{r.status==="triggered"&&<div className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800"><Check size={15} className="mr-1 inline"/>Reserva acionada. Próxima transição: alocação efetiva.</div>}</Card>})}</div></>}

function History({audit=false}:{audit?:boolean}){const data=audit?mockDb.audit:mockDb.history;return <><PageHeader title={audit?"Auditoria":"Histórico"} description={audit?"Registro administrativo de alterações e registros afetados.":"Linha do tempo operacional das ações realizadas."}/><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr>{audit?<><th className="px-5 py-3">Usuário</th><th className="px-5 py-3">Tipo</th><th className="px-5 py-3">Ação</th><th className="px-5 py-3">Registro</th><th className="px-5 py-3">Data/hora</th><th className="px-5 py-3">Alteração</th></>:<><th className="px-5 py-3">Data/hora</th><th className="px-5 py-3">Ação</th><th className="px-5 py-3">Entidade</th><th className="px-5 py-3">Responsável</th><th className="px-5 py-3">Descrição</th></>}</tr></thead><tbody className="divide-y divide-slate-100">{data.map(x=>audit?<tr key={x.id}><td className="px-5 py-4 font-medium">{x.user}</td><td className="px-5 py-4">{x.role}</td><td className="px-5 py-4"><Badge>{x.action}</Badge></td><td className="px-5 py-4">{x.entity}</td><td className="px-5 py-4 text-slate-500">{x.date}</td><td className="px-5 py-4">{x.change}</td></tr>:<tr key={x.id}><td className="px-5 py-4 text-slate-500">{x.date}</td><td className="px-5 py-4"><Badge>{x.action}</Badge></td><td className="px-5 py-4">{x.entity}</td><td className="px-5 py-4">{x.responsible}</td><td className="px-5 py-4">{x.description}</td></tr>)}</tbody></table></div></Card></>}

function Managers(){return <><PageHeader title="Gerentes" description="Usuários gerenciais e seus acessos mockados."/><div className="grid gap-4 md:grid-cols-2">{mockDb.managers.map(m=><Card key={m.id} className="p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-slate-100"><UserRound size={18}/></div><div><p className="font-semibold">{m.name}</p><p className="text-xs text-slate-500">{m.lastAccess}</p></div></div><Badge tone="success">{m.status}</Badge></div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><span className="text-sm text-slate-500">{m.permissionIds.length} permissões</span><Button variant="secondary">Editar permissões</Button></div></Card>)}</div></>}

function Permissions(){return <><PageHeader title="Acessos" description="Permissões individuais para gerentes. Administradores possuem acesso completo e não precisam de configuração."/><div className="grid gap-6 lg:grid-cols-2">{mockDb.managers.map(m=><Card key={m.id} className="p-5"><SectionTitle title={m.name} subtitle="Gerente · permissões mockadas"/><div className="space-y-3">{permissions.map(p=><label key={p.id} className="flex items-center justify-between gap-4 rounded-xl border border-slate-100 p-3"><span><span className="block text-sm font-medium">{p.label}</span><span className="text-xs text-slate-400">{p.group}</span></span><input type="checkbox" defaultChecked={m.permissionIds.includes(p.id)} className="size-4 accent-slate-900"/></label>)}</div></Card>)}</div></>}

function Opportunities(){return <><PageHeader title="Oportunidades" description="Somente vagas elegíveis para o seu perfil são exibidas."/><div className="grid gap-4 md:grid-cols-2">{getEligibleVacancies("e1").map(v=><OpportunityCard key={v.id} vacancy={v.id}/>)}</div></>}

function OpportunityCard({vacancy}:{vacancy:string}){const v=mockDb.vacancies.find(x=>x.id===vacancy)!;const ev=mockDb.events.find(x=>x.id===v.eventId)!;const existing=mockDb.applications.find(a=>a.employeeId==="e1"&&a.vacancyId===v.id);return <Card className="p-5"><div className="flex justify-between gap-3"><div><p className="font-semibold">{v.name}</p><p className="mt-1 text-sm text-slate-500">{ev.name} · {new Date(ev.date+"T12:00").toLocaleDateString("pt-BR")}</p></div><Badge tone={v.type==="reserve"?"warning":"info"}>{v.type==="reserve"?"Reserva":"Vaga normal"}</Badge></div><div className="mt-4 space-y-2 text-sm text-slate-600"><p><strong>Horário:</strong> chegada {ev.arrival} · {ev.start}–{ev.end}</p><p><strong>Local:</strong> {ev.location}</p><p><strong>Critérios:</strong> {v.levelId?labelFor(mockDb.levels,v.levelId):"Qualquer nível"} {v.skillIds.length?"+ "+(v.skillMatch==="all"?"todas":"qualquer uma")+" das habilidades: "+v.skillIds.map(s=>labelFor(mockDb.skills,s)).join(", "):""}</p><p><strong>Disponibilidade:</strong> {Math.max(0,v.quantity-v.filled)} de {v.quantity}</p></div><Button className="mt-5 w-full" disabled={!!existing} onClick={()=>{if(!existing){mockDb.applications.push({id:"new-"+Date.now(),employeeId:"e1",vacancyId:v.id,eventId:v.eventId,date:new Date().toISOString().slice(0,10),status:"Pendente"});window.location.reload()}}}>{existing?"Candidatura enviada":"Tenho interesse"}</Button></Card>}

function MyEvents(){const allocations=mockDb.allocations.filter(a=>a.employeeId==="e1"&&a.status==="Confirmada");return <><PageHeader title="Meus eventos" description="Somente eventos em que você está oficialmente alocada."/><div className="space-y-4">{allocations.map(a=>{const e=mockDb.events.find(x=>x.id===a.eventId)!;const v=mockDb.vacancies.find(x=>x.id===a.vacancyId)!;return <Card key={a.id} className="p-5"><div className="flex justify-between"><div><p className="text-lg font-semibold">{e.name}</p><p className="mt-1 text-sm text-slate-500">{new Date(e.date+"T12:00").toLocaleDateString("pt-BR")} · {e.location}</p></div><Badge tone={a.fromReserve?"warning":"success"}>{a.fromReserve?"SOBREAVISO / RESERVA":"Confirmado"}</Badge></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><div><p className="text-xs text-slate-400">Chegada</p><p className="font-medium">{e.arrival}</p></div><div><p className="text-xs text-slate-400">Início</p><p className="font-medium">{e.start}</p></div><div><p className="text-xs text-slate-400">Término</p><p className="font-medium">{e.end}</p></div><div><p className="text-xs text-slate-400">Função</p><p className="font-medium">{v.name}</p></div></div><div className="mt-5 border-t border-slate-100 pt-4"><p className="text-sm font-medium">Equipe confirmada</p><div className="mt-2 flex flex-wrap gap-2">{mockDb.allocations.filter(x=>x.eventId===e.id&&x.status==="Confirmada").map(x=><Badge key={x.id}>{employeeById(x.employeeId)?.name}</Badge>)}</div></div></Card>})}</div></>}

function MyApplications(){const apps=mockDb.applications.filter(a=>a.employeeId==="e1");return <><PageHeader title="Minhas candidaturas" description="Acompanhe somente as suas manifestações de interesse."/><div className="space-y-3">{apps.map(a=>{const v=mockDb.vacancies.find(x=>x.id===a.vacancyId)!;const e=mockDb.events.find(x=>x.id===a.eventId)!;return <Card key={a.id} className="flex items-center justify-between p-5"><div><p className="font-medium">{v.name}</p><p className="mt-1 text-sm text-slate-500">{e.name} · enviada em {a.date}</p></div><Badge tone={tone(a.status)}>{a.status}</Badge></Card>})}</div></>}

function Profile(){const e=employeeById("e1")!;return <><PageHeader title="Meu perfil" description="Informações profissionais liberadas para visualização."/><Card className="max-w-2xl p-6"><div className="flex items-center gap-4 border-b border-slate-100 pb-5"><div className="grid size-16 place-items-center rounded-full bg-slate-900 font-semibold text-white">{e.avatar}</div><div><h2 className="text-xl font-semibold">{e.name}</h2><p className="text-sm text-slate-500">{labelFor(mockDb.levels,e.levelId)}</p></div></div><div className="grid gap-5 py-5 sm:grid-cols-2"><div><p className="text-xs text-slate-400">Telefone</p><p className="mt-1 text-sm">{e.phone}</p></div><div><p className="text-xs text-slate-400">Nível</p><p className="mt-1 text-sm">{labelFor(mockDb.levels,e.levelId)}</p></div><div className="sm:col-span-2"><p className="text-xs text-slate-400">Habilidades</p><div className="mt-2 flex flex-wrap gap-2">{e.skillIds.map(s=><Badge key={s}>{labelFor(mockDb.skills,s)}</Badge>)}</div></div></div><div className="rounded-xl bg-slate-50 p-4"><p className="font-medium text-sm">Senha</p><p className="mt-1 text-xs text-slate-500">A alteração de senha é somente uma interface/mock nesta fase.</p><Button variant="secondary" className="mt-3">Alterar senha</Button></div></Card></>}

export default function Index(){const [role,setRole]=useState<Role>("admin");const [view,setView]=useState<View>("dashboard");const content=useMemo(()=>{switch(view){case"dashboard":return <Dashboard role={role}/>;case"employees":return <Employees/>;case"levels":return <LevelsOrSkills kind="levels"/>;case"skills":return <LevelsOrSkills kind="skills"/>;case"events":return <Events onView={setView}/>;case"calendar":return <CalendarView/>;case"applications":return <Applications/>;case"allocations":return <Allocations/>;case"standby":return <Standby/>;case"history":return <History/>;case"audit":return <History audit/>;case"managers":return <Managers/>;case"permissions":return <Permissions/>;case"opportunities":return <Opportunities/>;case"my-events":return <MyEvents/>;case"my-applications":return <MyApplications/>;case"profile":return <Profile/>;default:return <Dashboard role={role}/>}} , [view,role]);return <AppShell role={role} view={view} onView={setView} onRoleChange={r=>{setRole(r);setView("dashboard")}}>{content}</AppShell>}
